spring.application.name=customer-service

spring.datasource.url=jdbc:postgresql://localhost:5432/devsutest
spring.datasource.username=devsutest
spring.datasource.password=devsu2025*

server.port=8081

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.generate_statistics=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
