spring.application.name=account-service
server.port=8082

spring.datasource.url=jdbc:postgresql://postgres-db:5432/devsutest
spring.datasource.username=devsutest
spring.datasource.password=devsu2025*
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Configuración adicional para manejo de errores de conexión
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5 